import { v4 as uuidv4 } from "uuid";
import type { Task, Status, Priority } from "../types";

export const STATUSES: Status[] = ["todo", "in-progress", "done"];

export const PRIORITIES: Priority[] = ["low", "medium", "high"];

export const ASSIGNEE_LIST = [
  "John Doe",
  "Jane Smith",
  "Alice Johnson",
  "Bob Brown",
  "Carol White",
  "David Martinez",
  "Eva Wilson",
  "Frank Lee",
  "Grace Taylor",
  "Henry Clark",
];

export const TAGS_LIST = [
  "urgent",
  "bug",
  "feature",
  "design",
  "backend",
  "frontend",
  "testing",
  "docs",
  "refactor",
  "hotfix",
  "security",
  "performance",
];

// ─── Starter Mock Tasks (from assignment) ─────────────────────────────────

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Implement authentication",
    description: "Add JWT-based auth with refresh token support",
    status: "todo",
    priority: "high",
    assignee: "John Doe",
    tags: ["backend", "security"],
    createdAt: "2024-11-20T10:00:00Z",
    updatedAt: "2024-11-20T10:00:00Z",
    isOptimistic: false,
  },
  {
    id: "2",
    title: "Design new landing page",
    description: "Create mockups for homepage redesign with new branding",
    status: "in-progress",
    priority: "medium",
    assignee: "Jane Smith",
    tags: ["design", "frontend"],
    createdAt: "2024-11-19T14:30:00Z",
    updatedAt: "2024-11-19T14:30:00Z",
    isOptimistic: false,
  },
  {
    id: "3",
    title: "Fix payment gateway bug",
    description: "Users unable to complete checkout on mobile devices",
    status: "todo",
    priority: "high",
    assignee: "John Doe",
    tags: ["backend", "urgent"],
    createdAt: "2024-11-21T09:15:00Z",
    updatedAt: "2024-11-21T09:15:00Z",
    isOptimistic: false,
  },
  {
    id: "4",
    title: "Write unit tests for API layer",
    description: "Cover all REST endpoints with Jest test cases",
    status: "todo",
    priority: "medium",
    assignee: "Alice Johnson",
    tags: ["testing", "backend"],
    createdAt: "2024-11-18T08:00:00Z",
    updatedAt: "2024-11-18T08:00:00Z",
    isOptimistic: false,
  },
  {
    id: "5",
    title: "Optimize database queries",
    description: "Reduce average query time by adding proper indexes",
    status: "in-progress",
    priority: "high",
    assignee: "Bob Brown",
    tags: ["backend", "performance"],
    createdAt: "2024-11-17T11:00:00Z",
    updatedAt: "2024-11-17T11:00:00Z",
    isOptimistic: false,
  },
  {
    id: "6",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated deployment",
    status: "done",
    priority: "high",
    assignee: "Carol White",
    tags: ["backend", "docs"],
    createdAt: "2024-11-15T09:00:00Z",
    updatedAt: "2024-11-16T10:00:00Z",
    isOptimistic: false,
  },
  {
    id: "7",
    title: "Mobile responsive fixes",
    description: "Fix layout issues on screens smaller than 768px",
    status: "in-progress",
    priority: "medium",
    assignee: "Jane Smith",
    tags: ["frontend", "design"],
    createdAt: "2024-11-20T13:00:00Z",
    updatedAt: "2024-11-20T13:00:00Z",
    isOptimistic: false,
  },
  {
    id: "8",
    title: "Add dark mode support",
    description: "Implement system-aware dark/light theme toggle",
    status: "todo",
    priority: "low",
    assignee: "Eva Wilson",
    tags: ["frontend", "design"],
    createdAt: "2024-11-21T10:00:00Z",
    updatedAt: "2024-11-21T10:00:00Z",
    isOptimistic: false,
  },
  {
    id: "9",
    title: "Refactor user profile module",
    description: "Break down monolithic profile component into smaller pieces",
    status: "todo",
    priority: "low",
    assignee: "Frank Lee",
    tags: ["refactor", "frontend"],
    createdAt: "2024-11-19T16:00:00Z",
    updatedAt: "2024-11-19T16:00:00Z",
    isOptimistic: false,
  },
  {
    id: "10",
    title: "Update API documentation",
    description: "Sync Swagger docs with latest endpoint changes",
    status: "done",
    priority: "low",
    assignee: "Grace Taylor",
    tags: ["docs", "backend"],
    createdAt: "2024-11-14T09:00:00Z",
    updatedAt: "2024-11-15T12:00:00Z",
    isOptimistic: false,
  },
  {
    id: "11",
    title: "Implement email notifications",
    description: "Send transactional emails using SendGrid integration",
    status: "todo",
    priority: "medium",
    assignee: "David Martinez",
    tags: ["backend", "feature"],
    createdAt: "2024-11-21T11:00:00Z",
    updatedAt: "2024-11-21T11:00:00Z",
    isOptimistic: false,
  },
  {
    id: "12",
    title: "Code review for PR #42",
    description: "Review authentication PR before merging to main",
    status: "in-progress",
    priority: "high",
    assignee: "Henry Clark",
    tags: ["backend", "security"],
    createdAt: "2024-11-21T08:00:00Z",
    updatedAt: "2024-11-21T08:00:00Z",
    isOptimistic: false,
  },
  {
    id: "13",
    title: "Fix CORS issue on staging",
    description: "API calls failing from frontend due to CORS headers",
    status: "done",
    priority: "high",
    assignee: "Bob Brown",
    tags: ["bug", "backend", "urgent"],
    createdAt: "2024-11-16T14:00:00Z",
    updatedAt: "2024-11-16T16:30:00Z",
    isOptimistic: false,
  },
  {
    id: "14",
    title: "Accessibility audit",
    description: "Run axe-core audit and fix WCAG 2.1 AA violations",
    status: "todo",
    priority: "medium",
    assignee: "Alice Johnson",
    tags: ["frontend", "testing"],
    createdAt: "2024-11-20T15:00:00Z",
    updatedAt: "2024-11-20T15:00:00Z",
    isOptimistic: false,
  },
  {
    id: "15",
    title: "Integrate Stripe payments",
    description: "Replace legacy payment system with Stripe Checkout",
    status: "in-progress",
    priority: "high",
    assignee: "John Doe",
    tags: ["backend", "feature", "security"],
    createdAt: "2024-11-18T10:00:00Z",
    updatedAt: "2024-11-18T10:00:00Z",
    isOptimistic: false,
  },
  {
    id: "16",
    title: "Performance profiling",
    description: "Identify and fix render bottlenecks using React DevTools",
    status: "todo",
    priority: "medium",
    assignee: "Carol White",
    tags: ["frontend", "performance"],
    createdAt: "2024-11-21T12:00:00Z",
    updatedAt: "2024-11-21T12:00:00Z",
    isOptimistic: false,
  },
  {
    id: "17",
    title: "Add search functionality",
    description: "Full-text search across tasks and projects",
    status: "done",
    priority: "medium",
    assignee: "Eva Wilson",
    tags: ["feature", "frontend"],
    createdAt: "2024-11-13T09:00:00Z",
    updatedAt: "2024-11-14T11:00:00Z",
    isOptimistic: false,
  },
  {
    id: "18",
    title: "Set up error monitoring",
    description: "Integrate Sentry for production error tracking",
    status: "done",
    priority: "high",
    assignee: "Frank Lee",
    tags: ["backend", "frontend", "docs"],
    createdAt: "2024-11-12T10:00:00Z",
    updatedAt: "2024-11-13T09:00:00Z",
    isOptimistic: false,
  },
  {
    id: "19",
    title: "Write onboarding documentation",
    description: "Create developer setup guide for new team members",
    status: "in-progress",
    priority: "low",
    assignee: "Grace Taylor",
    tags: ["docs"],
    createdAt: "2024-11-20T09:00:00Z",
    updatedAt: "2024-11-20T09:00:00Z",
    isOptimistic: false,
  },
  {
    id: "20",
    title: "Implement rate limiting",
    description: "Add Redis-based rate limiting to public API endpoints",
    status: "todo",
    priority: "high",
    assignee: "David Martinez",
    tags: ["backend", "security", "performance"],
    createdAt: "2024-11-21T13:00:00Z",
    updatedAt: "2024-11-21T13:00:00Z",
    isOptimistic: false,
  },
  {
    id: "21",
    title: "Migrate to TypeScript",
    description: "Convert remaining JS files to TypeScript with strict mode",
    status: "in-progress",
    priority: "medium",
    assignee: "Henry Clark",
    tags: ["refactor", "frontend", "backend"],
    createdAt: "2024-11-17T14:00:00Z",
    updatedAt: "2024-11-17T14:00:00Z",
    isOptimistic: false,
  },
  {
    id: "22",
    title: "Fix memory leak in WebSocket handler",
    description: "Connections not being cleaned up on client disconnect",
    status: "todo",
    priority: "high",
    assignee: "Bob Brown",
    tags: ["bug", "backend", "urgent"],
    createdAt: "2024-11-21T07:00:00Z",
    updatedAt: "2024-11-21T07:00:00Z",
    isOptimistic: false,
  },
  {
    id: "23",
    title: "UI component library setup",
    description: "Configure Storybook for shared component documentation",
    status: "done",
    priority: "low",
    assignee: "Jane Smith",
    tags: ["frontend", "design", "docs"],
    createdAt: "2024-11-10T10:00:00Z",
    updatedAt: "2024-11-11T15:00:00Z",
    isOptimistic: false,
  },
  {
    id: "24",
    title: "Load testing with k6",
    description: "Simulate 1000 concurrent users and identify breaking points",
    status: "todo",
    priority: "medium",
    assignee: "Alice Johnson",
    tags: ["testing", "backend", "performance"],
    createdAt: "2024-11-21T14:00:00Z",
    updatedAt: "2024-11-21T14:00:00Z",
    isOptimistic: false,
  },
  {
    id: "25",
    title: "Implement file upload feature",
    description: "Allow users to attach files to tasks using S3 presigned URLs",
    status: "in-progress",
    priority: "medium",
    assignee: "Carol White",
    tags: ["feature", "backend", "frontend"],
    createdAt: "2024-11-19T10:00:00Z",
    updatedAt: "2024-11-19T10:00:00Z",
    isOptimistic: false,
  },
];

// ─── Generate a Single Random Task ────────────────────────────────────────

export const generateTask = (overrides?: Partial<Task>): Task => {
  const status = STATUSES[Math.floor(Math.random() * STATUSES.length)];
  const priority = PRIORITIES[Math.floor(Math.random() * PRIORITIES.length)];
  const assignee =
    ASSIGNEE_LIST[Math.floor(Math.random() * ASSIGNEE_LIST.length)];

  const shuffledTags = [...TAGS_LIST].sort(() => Math.random() - 0.5);
  const tags = shuffledTags.slice(0, Math.floor(Math.random() * 4));

  const createdAt = new Date(
    Date.now() - Math.floor(Math.random() * 30) * 24 * 60 * 60 * 1000,
  ).toISOString();

  return {
    id: uuidv4(),
    title: `Task ${Math.floor(Math.random() * 10000)}`,
    description: `This is an auto-generated task for performance testing purposes.`,
    status,
    priority,
    assignee,
    tags,
    createdAt,
    updatedAt: createdAt,
    isOptimistic: false,
    ...overrides,
  };
};

// ─── Generate Bulk Tasks (for 1000+ performance testing) ──────────────────

export const generateTasks = (count: number): Task[] => {
  return Array.from({ length: count }, () => generateTask());
};

// ─── Generate External Update for Real-Time Simulation ────────────────────

export const generateExternalUpdate = (existingTask: Task): Task => {
  const newStatus = STATUSES[Math.floor(Math.random() * STATUSES.length)];
  const newPriority = PRIORITIES[Math.floor(Math.random() * PRIORITIES.length)];

  return {
    ...existingTask,
    status: newStatus,
    priority: newPriority,
    updatedAt: new Date().toISOString(),
    isOptimistic: false,
  };
};
